 language: scala
 scala:
   - 2.10.3
   - 2.11.0-M5
 matrix:
   allow_failures:
     - scala: 2.11.0-M5
 jdk:
   - oraclejdk7
   - openjdk6
   - openjdk7
   
 script: "sbt ++$TRAVIS_SCALA_VERSION scalastyle test"
